<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldTawarHarga</name>
   <tag></tag>
   <elementGuidId>5c30b921-d01a-48de-89c9-fef239396131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='offer_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='offer_price']</value>
      <webElementGuid>3b01ee5f-95f5-43a4-bb10-d3c9de1223bf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
