<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectProduct</name>
   <tag></tag>
   <elementGuidId>694ad3db-51cb-49e4-8c5f-faf147543a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='products']/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='products']/div[1]</value>
      <webElementGuid>16bdba33-8c97-4a72-a73d-dacb8cd915e3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
