<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldemail</name>
   <tag></tag>
   <elementGuidId>9282f2bf-db81-4064-ac18-565a363cf6a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='user_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='user_email']</value>
      <webElementGuid>6b045e91-8970-4763-b933-6c697933886f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
