<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logoSS</name>
   <tag></tag>
   <elementGuidId>3eedfe20-d1d3-4b17-9c1e-fe43a98b84b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.navbar-brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.navbar-brand</value>
      <webElementGuid>42e5c27a-4afb-49bf-a5ce-7f5c8a51b789</webElementGuid>
   </webElementProperties>
</WebElementEntity>
