<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnJualHome</name>
   <tag></tag>
   <elementGuidId>f306bee0-17f9-414b-8587-cc732c993359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(.,'Jual')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(.,'Jual')]</value>
      <webElementGuid>2e56dcb2-4d12-4fca-bc18-0fe4085cb42b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
