<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldHargaJual</name>
   <tag></tag>
   <elementGuidId>8ba9581a-738a-472e-86fa-1423d26f13e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='product_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='product_price']</value>
      <webElementGuid>8c8aca06-f709-4047-b5ae-00e52e358b27</webElementGuid>
   </webElementProperties>
</WebElementEntity>
