<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldKategoriJual</name>
   <tag></tag>
   <elementGuidId>3b814917-4eb3-41c5-af7f-020bc6fc2820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='product_category_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='product_category_id']</value>
      <webElementGuid>6bf30493-ccea-42bb-86a3-4d90bb6d0dd5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
