<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldNamaJual</name>
   <tag></tag>
   <elementGuidId>bda4ba9f-9d0f-4f7f-970d-cba9ed0094d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='product_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='product_name']</value>
      <webElementGuid>8c867662-3efc-46f8-aa8b-0958a0f1aad2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
