<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>humburgericon</name>
   <tag></tag>
   <elementGuidId>bd7353e2-679c-41ee-8a8d-e57f312186ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.bi-list-ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.bi-list-ul</value>
      <webElementGuid>1cccead2-a4f9-4f85-a6de-2dd025568cfc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
