<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldHarga</name>
   <tag></tag>
   <elementGuidId>8cebcbf6-e7ac-4fa9-8bae-8756bddf280f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='product_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='product_price']</value>
      <webElementGuid>72d05213-792d-4db9-908d-04407589575e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
