<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldCategory</name>
   <tag></tag>
   <elementGuidId>44237c9c-ebbb-41a4-912e-1ecb5aabc7cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='product_category_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='product_category_id']</value>
      <webElementGuid>78868e7a-963f-48f7-a7aa-0372963fec9a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
