<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filedDescription</name>
   <tag></tag>
   <elementGuidId>6ff548b9-33df-4936-8661-a6da78277356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='product_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='product_description']</value>
      <webElementGuid>8d53ab09-f3d7-4de7-9110-b9463fc17aa3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
