<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnmasuk</name>
   <tag></tag>
   <elementGuidId>bfb476af-43e3-4bb9-a76a-4e8bf21e4f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(.,'Masuk')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(.,'Masuk')]</value>
      <webElementGuid>5c934a41-9028-4e4d-93dd-8724a251905f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
