<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>daftarjual</name>
   <tag></tag>
   <elementGuidId>14be9332-9975-4538-a565-a71404f4c4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.pt-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.pt-5</value>
      <webElementGuid>106abe59-10f7-4ff1-9e2d-48b87ea1fe72</webElementGuid>
   </webElementProperties>
</WebElementEntity>
