<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_random_2</name>
   <tag></tag>
   <elementGuidId>6c89ba9e-954b-40c3-95a7-a2620ada08b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.card-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.card-title</value>
      <webElementGuid>1c7f72ae-2bdc-443d-8928-a180b9a3e265</webElementGuid>
   </webElementProperties>
</WebElementEntity>
