<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectedAvaliableProduct</name>
   <tag></tag>
   <elementGuidId>a93069ec-57ed-45b7-b40c-1750694bcc4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h5[@class='card-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h5[@class='card-title']</value>
      <webElementGuid>1a64b732-4f87-4cf3-8668-c46758f8c86a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
