<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldnama</name>
   <tag></tag>
   <elementGuidId>ca276525-c868-4697-81f9-c37f5b9378e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='user_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='user_name']</value>
      <webElementGuid>3f1c4376-409b-4a3e-92d8-3ece0b48a137</webElementGuid>
   </webElementProperties>
</WebElementEntity>
