<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldkota</name>
   <tag></tag>
   <elementGuidId>7f4a4107-c884-4629-9de7-953d8393b9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='user_city_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='user_city_id']</value>
      <webElementGuid>afbcdedc-2313-4a94-adea-12fbcac08486</webElementGuid>
   </webElementProperties>
</WebElementEntity>
