<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listTerjual</name>
   <tag></tag>
   <elementGuidId>a3dd68b6-cdf4-4482-9914-d308658933a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@src='/empty-product.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@src='/empty-product.svg']</value>
      <webElementGuid>647385a3-599f-461b-a1f0-0df6b9c4d46f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
