<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldPasswordDaftar</name>
   <tag></tag>
   <elementGuidId>ee4b2374-fff4-4e6c-b767-016b487a1832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='user_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='user_password']</value>
      <webElementGuid>e92df2f0-7ea3-45db-957e-3514c8fe0f4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
