<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldNameDaftar</name>
   <tag></tag>
   <elementGuidId>c1126efc-9864-46d7-b322-bcc1b9e61c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='user_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='user_name']</value>
      <webElementGuid>8b13b416-64c3-4418-80cc-f9dbb2bfd720</webElementGuid>
   </webElementProperties>
</WebElementEntity>
